# Generated by Django 5.0.6 on 2024-05-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='user',
            new_name='requested_by',
        ),
    ]
